package:
  format-version: "1.0.0"
  name: "core_apps_pic32ck_sg_gc"
  version: "v3.1.1"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "bsp"
      type: "package"
      version: "v3.23.0"
    - name: "FreeRTOS-Kernel"
      type: "package"
      version: "V11.1.0"
    - name: "core"
      type: "package"
      version: "v3.15.5"
